# AutoVulnScan Configuration File
# This file contains all the settings for the AutoVulnScan application.
# For more information on configuring AutoVulnScan, please refer to the documentation.

# Debug enables verbose logging, which is useful for development and troubleshooting.
# Default: false
debug: true

# Proxy sets the proxy server for all outbound HTTP requests.
# Example: "http://127.0.0.1:8080"
proxy: ""

# Headers specifies custom HTTP headers to be included in every request sent by the scanner.
# This is useful for setting custom User-Agent strings or authentication tokens.
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

scope:
  - "testphp.vulnweb.com"
blacklist:
  - "\\.js$"
  - "\\.css$"

spider:
  # Concurrency determines how many spider instances run simultaneously.
  # Higher values can speed up crawling but may increase resource usage.
  concurrency: 10
  # Limit sets the maximum number of pages to be crawled.
  limit: 100
  # Timeout specifies the maximum duration (in seconds) for a spider's request to complete.
  timeout: 10
  # MaxDepth defines the maximum depth of directories the spider will crawl.
  max_depth: 5
  # MaxPageVisitPerSite limits the number of pages the spider will visit on a single site.
  max_page_visit_per_site: 10
  # Cookies allows you to specify cookies for the spider to use, which can be helpful for authenticated scans.
  # Example:
  #   '*.testphp.vulnweb.com': "cookie1=1;cookie2=2"
  cookies:
    cookie_name: "cookie_value"
  # SimilarityPageDom helps the spider avoid crawling duplicate pages by comparing their DOM structures.
  similarity_page_dom:
    # Use enables or disables the DOM similarity check.
    use: true
    # Threshold is the minimum number of DOM elements required to perform a similarity check.
    threshold: 100
    # Similarity is the threshold (from 0.0 to 1.0) for pages to be considered duplicates.
    similarity: 0.9
    # VectorDim is the dimension of the vector used for similarity calculations.
    vector_dim: 64
  # DynamicCrawler configures the headless browser for crawling JavaScript-heavy websites.
  dynamic_crawler:
    # Enabled activates the dynamic crawler.
    enabled: true
    # Headless runs the browser without a graphical user interface.
    headless: true
  # Sources specifies where the spider should look for URLs to crawl.
  sources:
    - "robotstxt"
    - "sitemapxml"

# Scanner configuration settings for the vulnerability scanning phase.
scanner:
  # Concurrency sets the number of concurrent scan tasks.
  concurrency: 100
  # Limit defines the maximum number of URLs to be scanned.
  limit: 50
  # FilterThreshold is used to filter out similar pages to avoid redundant scanning.
  filter_threshold: 50
  # FoundHiddenParameter enables the scanner to look for hidden parameters in web pages.
  found_hidden_parameter: true
  # FoundHiddenParameterFromJS enables searching for hidden parameters within JavaScript files.
  found_hidden_parameter_from_js: false
  # ParameterGroupSize specifies how many parameters to group together in a single test.
  parameter_group_size: 40
  # Timeout sets the maximum duration (in seconds) for a scan request.
  timeout: 30
  # PluginTimeout sets the timeout for individual plugins.
  plugin_timeout: 20
  # Position specifies where the scanner should inject payloads (e.g., "get", "post", "uri").
  position:
    - "get"
    - "post"
    - "uri"
  # Output determines what information is included in the scan report.
  output:
    response: false
    response_header: true
  # HiddenParameters is a list of parameter names that the scanner should specifically look for.
  hidden_parameters:
    - "key"
    - "redirect"
    - "action"
    - "id"
    - "page"
    - "search"
    - "query"
    - "keyword"
    - "q"
    - "s"
    - "token"
    - "file"
    - "path"
    - "url"
    - "return"
    - "next"
    - "target"
  # Vulnerabilities defines the types of vulnerabilities to scan for and their corresponding payloads.
  vulnerabilities:
    - type: "sqli"
      payloads:
        - value: "'"
          description: "Apostrophe, basic check for unescaped strings"
        - value: "\""
          description: "Double quote, basic check for unescaped strings"
        - value: "' OR 1=1 --"
          description: "Classic boolean-based blind SQLi"
        - value: "' OR '1'='1"
          description: "Another classic boolean-based blind SQLi"
    - type: "xss"
      payloads:
        - value: "<script>alert('AutoVulnScanXSS')</script>"
          description: "Basic XSS"
        - value: "<img src=x onerror=alert('AutoVulnScanXSS')>"
          description: "Image-based XSS"
        - value: "&lt;script&gt;alert('AutoVulnScanXSS')&lt;/script&gt;"
          description: "HTML-encoded XSS"

# Reporting configuration for generating scan reports.
reporting:
  # Path is the directory where the reports will be saved.
  path: "reports/"
  # VulnReportFile is the name of the file for discovered vulnerabilities.
  vuln_report_file: "vuln_report.txt"
  # SpiderFile is the name of the file for all crawled URLs.
  spider_file: "spider_results.txt"
  # UnscopedSpiderFile is the name of the file for out-of-scope URLs.
  unscoped_spider_file: "unscoped_spider_results.txt"
  # SpiderDeDuplicateFile is the name of the file for de-duplicated URLs.
  spider_deduplicate_file: "spider_deduplicate_results.txt"
  # SpiderParamsFile is the name of the file for URLs with parameters.
  spider_params_file: "spider_params_results.txt"
  json_report_file: "report.json"
  html_report_file: "report.html"

# Redis configuration for using Redis as a backend for storing scan data.
redis:
  # Enabled activates the Redis connection.
  enabled: false
  # URL is the connection string for the Redis server.
  url: "redis://localhost:6379/0"

# AIModule configuration for using AI-powered analysis.
ai_module:
  # Enabled activates the AI module.
  enabled: false
  # Model specifies the AI model to be used for analysis.
  model: "deepseek/deepseek-v3"
  # APIKey is the API key for the AI service.
  api_key: "sk-bb716bfbdb56496aa8eba12fd7400a70"
