target:
  url: "http://testphp.vulnweb.com/"
  depth: 2
  allowed_domains:
    - "testphp.vulnweb.com"
  exclude_paths:
    - "/logout.php"
  auth:
    type: "none"
    value: ""

scanner:
  concurrency: 10
  timeout: 30
  retries: 3
  rate_limit: 100 # requests per second
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

reporting:
  format: ["json", "html"]
  path: "reports" # For HTML/JSON this is a directory, for Redis this could be the connection string

ai_module:
  enabled: false
  model: "gpt-3.5-turbo"
  api_key: "YOUR_API_KEY_HERE"

vulnerabilities:
  - type: "sqli"
    parameters: ["id", "cat", "search"]
  - type: "xss"
    parameters: ["name", "comment", "query"] 