target:
  url: "http://testphp.vulnweb.com/"
  depth: 2
  allowed_domains:
    - "testphp.vulnweb.com"
  exclude_paths:
    - "/logout.php"
  auth:
    type: "none"
    value: ""

scanner:
  concurrency: 10
  timeout: 10
  retries: 3
  rate_limit: 100 # requests per second
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "AutoVulnScan/1.0"
  similarity_threshold: 0.95

reporting:
  format: ["json", "html"] # Supported formats: json, html
  path: "reports" # For HTML/JSON this is a directory, for Redis this could be the connection string

ai:
  api_key: "sk-bb716bfbdb56496aa8eba12fd7400a70"
  model: "deepseek/deepseek-v3"
  base_url: "https://api.deepseek.com" # For local models like Ollama, use e.g., "http://localhost:11434/v1"

vulnerabilities:
  - type: sqli
    enabled: true
  - type: xss
    enabled: true
    parameters: ["name", "comment", "query"] 