debug: true
proxy: ""

<<<<<<< HEAD
scanner:
  concurrency: 10
  timeout: 10
  retries: 3
  rate_limit: 100 # requests per second
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "AutoVulnScan/1.0"
  similarity_threshold: 0.95

reporting:
  format: ["json", "html"] # Supported formats: json, html
  path: "reports" # For HTML/JSON this is a directory, for Redis this could be the connection string

ai:
  api_key: "sk-bb716bfbdb56496aa8eba12fd7400a70"
  model: "deepseek/deepseek-v3"
  base_url: "https://api.deepseek.com" # For local models like Ollama, use e.g., "http://localhost:11434/v1"

vulnerabilities:
  - type: sqli
    enabled: true
  - type: xss
    enabled: true
    parameters: ["name", "comment", "query"] 
=======
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

spider:
  concurrency: 100
  limit: 50
  timeout: 30
  max_depth: 15
  max_page_visit_per_site: 2000
  scope:
    - "testphp.vulnweb.com"
  blacklist:
    - ".google.com"
    - ".facebook.com"
    - ".googleapis.com"
    - ".gstatic.com"
    - ".jquery.com"
    - ".cloudflare.com"
    - ".jsdelivr.net"
    - ".twitter.com"
    - ".linkedin.com"
  # cookies:
  #   '*.testphp.vulnweb.com': "cookie1=1;cookie2=2"
  similarity_page_dom:
    use: true
    threshold: 5
    similarity: 0.95
    vector_dim: 5000
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15"
  dynamic_crawler:
    enabled: true
    headless: true
  sources:
    - "robotstxt"
    - "sitemapxml"

scan:
  concurrency: 100
  limit: 50
  filter_threshold: 50
  hidden_parameters:
    - "key"
    - "redirect"
    - "action"
    - "id"
    - "page"
    - "search"
    - "query"
    - "keyword"
    - "q"
    - "s"
    - "token"
    - "file"
    - "path"
    - "url"
    - "return"
    - "next"
    - "target"
  positions:
    - "get"
    - "post"
    - "uri"
  timeout: 30

reporting:
  path: "reports/"
  vuln_report_file: "urls-Vulns.txt"
  spider_file: "urls-spider.txt"
  spider_deduplicate_file: "urls-spider_de-duplicate_all.txt"
  spider_params_file: "urls-spider_params.txt"

redis:
  enabled: false
  url: "redis://localhost:6379/0"

ai_module:
  enabled: false
  model: "deepseek/deepseek-v3"
  api_key: "sk-bb716bfbdb56496aa8eba12fd7400a70"

vulnerabilities:
  - type: "sqli"
  - type: "xss" 
>>>>>>> f6b10a3508eb495bb38eddd523b9e76494383b16
